#!/bin/bash

echo "╔══════════════════════════════════╗"
echo "║           KKP Workshop           ║"
echo "╚══════════════════════════════════╝"
echo ""
echo "installed tools:"
echo "  zsh       $(zsh --version 2>/dev/null | awk '{print $2}')"
echo "  kubectl   $(kubectl version --client --output=yaml 2>/dev/null | grep gitVersion | awk '{print $2}')"
echo "  krew      $(kubectl krew version 2>/dev/null | grep GitTag | awk '{print $2}')"
echo "  helm      $(helm version --short 2>/dev/null)"
echo "  helmfile  $(helmfile version -o=short 2>/dev/null)"
echo "  kubectx   $(kubectx --version 2>/dev/null)"
echo "  gcloud    $(gcloud version --format="value('Google Cloud SDK')" 2>/dev/null)"
echo "  terraform $(terraform version 2>/dev/null | head -1 | awk '{print $2}')"
echo "  yq        $(yq --version 2>/dev/null | awk '{print $NF}')"
echo "  kubeone   $(kubeone version 2>/dev/null | grep -m1 gitVersion | grep -oE '[0-9]+\.[0-9]+\.[0-9]+')"
echo "  velero    $(velero version --client-only 2>/dev/null | awk '/Version:/{print $2; exit}')"
echo ""
