apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: blue
          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          imagePullPolicy: Always
          tty: true
          stdin: true
          ports:
            - name: http
              containerPort: 8080
          livenessProbe:
            httpGet:
              path: /liveness/
              port: 8080
          readinessProbe:
            httpGet:
              path: /readiness/
              port: 8080
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi
          volumeMounts:
            - name: my-volume
              mountPath: /app/training-application.conf
              subPath: training-application.conf
      volumes:
        - name: my-volume
          configMap:
            name: my-app
